import { JudicialAsset } from './types'

export const MOCK_ASSETS: JudicialAsset[] = [
  {
    id: '1',
    processNumber: '0004194-38.2015.4.01.3400',
    party: 'UNIÃO FEDERAL/DNER',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 3298354.25,
    referenceDate: '2017-05-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Ação ordinária visando a cobrança de reajustes contratuais e diferenças de medição decorrentes de atrasos nos repasses financeiros pela autarquia, resultando em desequilíbrio econômico-financeiro.',
    estimatedRecoveryTime: '3 a 5 anos',
    lastDevelopments: 'Aguardando julgamento de Recurso de Apelação interposto pela União.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '2',
    processNumber: '0001710-23.2005.8.26.0053',
    party: 'DER/SP',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 17500000.0,
    valueDetails: 'Estimativa R$ 15M a R$ 20M',
    referenceDate: '2023-10-15',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação de cobrança referente a custos extraordinários incorridos na execução de obras rodoviárias, não reconhecidos administrativamente.',
    estimatedRecoveryTime: '2 a 4 anos',
    lastDevelopments:
      'Fase de liquidação de sentença. Perícia contábil em andamento para apuração do quantum debeatur.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '3',
    processNumber: '0016557-47.1998.8.14.0301',
    party: 'ESTADO DO PARÁ',
    court: 'Tribunal de Justiça - PA',
    lawyer: 'Sayão & Polo',
    value: 21475522.72,
    referenceDate: '2024-10-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação indenizatória por rescisão unilateral de contrato administrativo e ausência de pagamento por serviços já executados e medidos.',
    estimatedRecoveryTime: '1 a 2 anos',
    lastDevelopments:
      'Precatório expedido, aguardando inclusão na fila de pagamentos do ente estadual.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '4',
    processNumber: '0025995-17.2004.8.26.0053',
    party: 'DER/SP & FAZENDA',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 666899577.0,
    valueDetails: 'Incontroverso: R$ 31.959.498,30 / Controverso: R$ 634.940.078,70',
    referenceDate: '2024-01-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Recomposição do equilíbrio econômico-financeiro de diversos contratos firmados com o DER/SP, abarcando custos indiretos, prorrogações e reajustamentos incorretos.',
    estimatedRecoveryTime: 'Acima de 5 anos',
    lastDevelopments:
      'Expedido ofício requisitório do valor incontroverso. Parte controversa aguarda julgamento de Agravo de Instrumento.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '5',
    processNumber: '0156487-94.2016.8.06.0001',
    party: 'ESTADO DO CEARÁ',
    court: 'Vara da Fazenda Pública - CE',
    lawyer: 'Sayão & Polo',
    value: 46852535.3,
    referenceDate: '2025-05-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação de cobrança de faturas não adimplidas e pleito indenizatório por permanência de canteiro além do prazo contratual original.',
    estimatedRecoveryTime: '2 a 4 anos',
    lastDevelopments:
      'Apresentação de alegações finais. Processo concluso para sentença de primeira instância.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '6',
    processNumber: '1004309-37.2018.4.01.3400',
    party: 'DNIT',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 50046156.78,
    valueDetails: 'Sentença: R$ 45.403.566,08 / Apelação: R$ 50.046.156,78',
    referenceDate: '2026-04-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação ordinária visando a recomposição do equilíbrio econômico-financeiro do contrato DIF nº 008/2008 (CFA). O prazo de execução foi estendido de 720 para 2.420 dias devido a falhas da Administração (revisões de projeto, atrasos na liberação de insumos e desapropriações). Laudos periciais de engenharia e contabilidade convergentes em favor do pleito.',
    estimatedRecoveryTime: '2 a 3 anos',
    lastDevelopments:
      'Ação julgada procedente com a seguinte sentença: "JULGO PROCEDENTE O PEDIDO... para CONDENAR o DNIT a pagar à CETENCO ENGENHARIA S.A. o valor de R$ 45.403.566,08... atualizado e acrescido de juros de mora a partir de março de 2023." Atualmente, aguarda-se o julgamento de Embargos de Declaração opostos pelo DNIT e Recurso de Apelação interposto pela Cetenco, buscando a majoração para R$ 50.046.156,78.',
    lastUpdate: '2026-04-20',
    history: [
      {
        id: 'h1',
        date: '2023-03-15',
        description:
          'Laudos periciais (Engenharia e Contábil) encartados aos autos, com conclusões convergentes atestando o desequilíbrio econômico-financeiro por culpa exclusiva da Administração.',
        author: 'Sayão & Polo',
      },
      {
        id: 'h2',
        date: '2025-11-10',
        description:
          'Sentença de mérito proferida: "JULGO PROCEDENTE O PEDIDO... para CONDENAR o DNIT a pagar à CETENCO ENGENHARIA S.A. o valor de R$ 45.403.566,08... atualizado e acrescido de juros de mora a partir de março de 2023."',
        author: 'Sayão & Polo',
      },
      {
        id: 'h3',
        date: '2025-12-05',
        description: 'Oposição de Embargos de Declaração pelo DNIT alegando omissões genéricas.',
        author: 'Sayão & Polo',
      },
      {
        id: 'h4',
        date: '2026-02-20',
        description:
          'Interposição de Recurso de Apelação pela Cetenco visando a adequação de rubricas não contempladas integralmente, pleiteando o valor total de R$ 50.046.156,78.',
        author: 'Sayão & Polo',
      },
    ],
  },
  {
    id: '7',
    processNumber: '1034623-16.2020.8.26.0053',
    party: 'FAZENDA SP',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 31996568.35,
    referenceDate: '2024-10-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação anulatória de débito fiscal estadual (ICMS) com repetição de indébito sobre aquisição de maquinário.',
    estimatedRecoveryTime: '2 a 3 anos',
    lastDevelopments: 'Sentença favorável em primeiro grau. Fazenda interpôs recurso de apelação.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '8',
    processNumber: '1033867-41.2019.8.26.0053',
    party: 'FAZENDA SP',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 4000000.0,
    referenceDate: '2019-07-01',
    risk: 'Remoto',
    status: 'Ativo',
    summary: 'Impugnação de auto de infração ambiental lavrado em obra rodoviária estadual.',
    estimatedRecoveryTime: '4 a 6 anos',
    lastDevelopments: 'Aguardando julgamento no Tribunal de Justiça de São Paulo (TJSP).',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '9',
    processNumber: '5027559-54.2022.4.04.7200',
    party: 'DNIT',
    court: 'Justiça Federal - SC',
    lawyer: 'Sayão & Polo',
    value: 160000000.0,
    referenceDate: '2022-09-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Ação indenizatória de grande vulto discutindo recomposição de reajustamento, juros de mora por atraso de pagamentos e extensão de prazo (overhead).',
    estimatedRecoveryTime: 'Acima de 5 anos',
    lastDevelopments:
      'Fase postulatória concluída. Juízo analisa preliminares suscitadas pelo DNIT na contestação.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '10',
    processNumber: '0032392-47.1999.4.01.3400',
    party: 'ITAIPU',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 414161262.2,
    referenceDate: '2024-10-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Cobrança de diferenças de correção monetária incidentes sobre faturas pagas em atraso durante a construção da Usina Hidrelétrica de Itaipu.',
    estimatedRecoveryTime: '1 a 3 anos',
    lastDevelopments:
      'Discussão no STJ acerca dos índices de correção aplicáveis. Agravo Interno pendente de julgamento.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '11',
    processNumber: '0018043-63.2004.4.01.3400',
    party: 'UNICON/ITAIPU',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 27546148.27,
    referenceDate: '2023-01-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Lide decorrente de consórcio construtor (UNICON) contra a Itaipu Binacional, pleiteando verbas complementares de administração local.',
    estimatedRecoveryTime: '3 a 5 anos',
    lastDevelopments:
      'Processo suspenso aguardando resolução de tema repetitivo com repercussão geral nos Tribunais Superiores.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '12',
    processNumber: '0034683-83.2000.4.01.3400',
    party: 'ITAIPU',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 26648483.18,
    referenceDate: '2023-01-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Cobrança por obras complementares e custos adicionais decorrentes de modificações de projeto não contempladas no aditivo contratual principal.',
    estimatedRecoveryTime: '3 a 5 anos',
    lastDevelopments:
      'Perícia complementar requerida para esclarecer divergências técnicas apontadas pelos assistentes técnicos.',
    lastUpdate: '2023-11-20',
    history: [],
  },
  {
    id: '13',
    processNumber: '0032393-32.1999.4.01.3400',
    party: 'ITAIPU',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 649420695.7,
    referenceDate: '2023-01-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Maior pleito do portfólio. Discussão sobre a metodologia de reajuste tarifário e indexadores previstos no tratado internacional aplicados aos pagamentos do consórcio.',
    estimatedRecoveryTime: 'Acima de 5 anos',
    lastDevelopments:
      'Remessa dos autos à instância superior (TRF1) para julgamento das apelações cruzadas. Tentativas preliminares de conciliação infrutíferas.',
    lastUpdate: '2023-11-20',
    history: [],
  },
]
