import { JudicialAsset } from './types'

export const MOCK_ASSETS: JudicialAsset[] = [
  {
    id: '1',
    processNumber: '5027559-54.2022.4.04.7200',
    party: 'DNIT',
    court: 'Justiça Federal - SC (RJS)',
    lawyer: 'Sayão & Polo',
    value: 160000000.0,
    incontroversoValue: 0,
    controversoValue: 160000000.0,
    expectedGain: 80000000.0,
    gainPercentage: 50,
    referenceDate: '2022-09-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Ação indenizatória visando a recomposição do Equilíbrio Econômico-Financeiro do contrato e impactos no BDI devido a atrasos decorrentes da Administração.',
    estimatedRecoveryTime: 'Acima de 5 anos',
    lastDevelopments: 'Atualmente na fase de Instrução Probatória/Perícia.',
    lastUpdate: '2023-11-20',
    sortOrder: 1,
    history: [
      {
        id: 'h1',
        date: '2023-11-01',
        description:
          'Início da fase de Instrução Probatória/Perícia técnica para avaliação dos impactos no BDI.',
        author: 'Sayão & Polo',
      },
    ],
  },
  {
    id: '2',
    processNumber: '1034623-16.2020.8.26.0053 / 1033867-41.2019.8.26.0053',
    party: 'FAZENDA SP',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 31996568.35,
    incontroversoValue: 10000000.0,
    controversoValue: 21996568.35,
    expectedGain: 25597254.68,
    gainPercentage: 80,
    valueDetails: 'Valor Histórico: R$ 13.297.886,90 / Atualizado Cetenco (35%): R$ 31.996.568,35',
    referenceDate: '2024-10-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ações conexas discutindo repetição de indébito e cobranças. Laudo Pericial favorável à Autora reconhecendo o direito quanto à alteração da alíquota de ISS e medições de faturas não pagas.',
    estimatedRecoveryTime: '2 a 3 anos',
    lastDevelopments:
      'Apresentação do Laudo Pericial favorável, aguardando manifestação da parte contrária.',
    lastUpdate: '2023-11-20',
    sortOrder: 2,
    history: [],
  },
  {
    id: '3',
    processNumber: '0025995-17.2004.8.26.0053',
    party: 'DER/SP',
    court: 'Vara da Fazenda Pública - SP',
    lawyer: 'Sayão & Polo',
    value: 634940078.7,
    incontroversoValue: 31900000.0,
    controversoValue: 603040078.7,
    expectedGain: 317470039.35,
    gainPercentage: 50,
    valueDetails: 'Laudo Pericial: Tese DER R$ 31,9M vs. Tese Cetenco R$ 634,9M',
    referenceDate: '2024-01-01',
    risk: 'Possível',
    status: 'Ativo',
    summary:
      'Recomposição do equilíbrio econômico-financeiro. O laudo pericial apresenta cenário com dupla hipótese: Tese DER (R$ 31,9M) vs. Tese Cetenco (R$ 634,9M). Houve Trânsito em Julgado quanto ao cômputo dos juros, estabelecendo que devem incidir a partir do evento danoso, e não da citação.',
    estimatedRecoveryTime: 'Acima de 5 anos',
    lastDevelopments:
      'Trânsito em julgado parcial sobre a incidência de juros a partir do evento danoso.',
    lastUpdate: '2023-11-20',
    sortOrder: 3,
    history: [],
  },
  {
    id: '4',
    processNumber: '0000157-76.1999.4.01.3901',
    party: 'RONDHEVEA / INCRA',
    court: 'TRF1',
    lawyer: 'Sayão & Polo',
    value: 45000000.0,
    incontroversoValue: 45000000.0,
    controversoValue: 0.0,
    expectedGain: 40500000.0,
    gainPercentage: 90,
    referenceDate: '2023-05-10',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação de desapropriação e indenização. Tese de julgamento firmada no TRF contendo os 6 pontos: 1. Legitimidade; 2. Competência; 3. Interesse; 4. Propriedade; 5. Má-fé; 6. Honorários Advocatícios. Destaca-se o pleno reconhecimento da legitimidade da Cetenco sobre os créditos excedentes à oferta inicial.',
    estimatedRecoveryTime: '1 a 3 anos',
    lastDevelopments:
      'Julgamento favorável no TRF1 confirmando a legitimidade da Cetenco para levantamento dos valores.',
    lastUpdate: '2023-11-20',
    sortOrder: 4,
    history: [],
  },
  {
    id: '5',
    processNumber: '1004309-37.2018.4.01.3400',
    party: 'DNIT',
    court: 'Justiça Federal - DF',
    lawyer: 'Sayão & Polo',
    value: 50046156.78,
    incontroversoValue: 45403566.08,
    controversoValue: 4642590.7,
    expectedGain: 45403566.08,
    gainPercentage: 90,
    valueDetails: 'Sentença: R$ 45.403.566,08 / Apelação: R$ 50.046.156,78',
    referenceDate: '2026-04-01',
    risk: 'Provável',
    status: 'Ativo',
    summary:
      'Ação ordinária visando a recomposição do equilíbrio econômico-financeiro do contrato DIF nº 008/2008 (CFA). O prazo de execução foi estendido de 720 para 2.420 dias devido a falhas da Administração. Laudos periciais de engenharia e contabilidade convergentes em favor do pleito.',
    estimatedRecoveryTime: '2 a 3 anos',
    lastDevelopments:
      'Ação julgada procedente com a seguinte sentença: "JULGO PROCEDENTE O PEDIDO... para CONDENAR o DNIT a pagar à CETENCO ENGENHARIA S.A. o valor de R$ 45.403.566,08... atualizado e acrescido de juros de mora a partir de março de 2023." Aguarda-se julgamento de Apelação buscando a majoração.',
    lastUpdate: '2026-04-20',
    sortOrder: 5,
    history: [
      {
        id: 'h1',
        date: '2025-11-10',
        description: 'Sentença de mérito proferida condenando o DNIT a pagar R$ 45.403.566,08.',
        author: 'Sayão & Polo',
      },
    ],
  },
]
